### ISSUE TITLE
Critical flaw

### ISSUE THREAD

**Issue by jooapa** [miskamero/count-code-lines#1]
I have found a critical flaw in this repository. It will scan all the file in the folder. This is a problem when it will start counting lines from in example node_modules folder. I can propose a change for this. I.e you could remove the folders found from the gitignore file

Nöfnöf

**Comment by miskamero** [comment]
nöfnöf

**Comment by jooapa** [comment]
how dare you miss this important flaw in your code, klinoff will not be happy to hear this!! 
![kuva](https://github.com/miskamero/count-code-lines/assets/37744313/f12e631e-823d-490a-89d9-97e3133fa937)

nöfnöf
