### ISSUE TITLE
Clear mistake on the README.md

### ISSUE THREAD

**Issue by jooapa** [miskamero/count-code-lines#2]
### Keyboard shortcut

If you have the extenion installed, you can press `Ctrl + Alt + Z` to count the lines of code in the current file.
The default keyboard shortcut can be changed in the VSCode settings.

this is clearly wrong, because shortcut `Ctrl + Alt + Z` is used for the most recent command ran on the vscode and not specifically on your extension, please fix this

**Comment by miskamero** [comment]
It is your custom keybind. Not a default VSCode bind.
[Default Windows bind](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf)
[Some StackOverflow question, same topic](https://stackoverflow.com/questions/51980406/visual-studio-code-command-for-repeat-last-command)

**Comment by jooapa** [comment]
![kuva](https://github.com/miskamero/count-code-lines/assets/37744313/3972f713-e025-4d3b-863b-e46a051c7da0)
