### ISSUE TITLE
OBSOLETE Extension

### ISSUE THREAD

**Issue by jooapa** [miskamero/count-code-lines#3]
COde can be done without downloading random crap, and is cross-platform, using the git bash on windows or on unix systems 
```bash
git ls-files | xargs cat | wc -l
```

**Comment by jooapa** [comment]
and is faster

**Comment by miskamero** [comment]
This extension is meant to serve one simple purpose; To guide beginners. It is a good solution to a trivial problem.

**Comment by jooapa** [comment]
Im not doubting the fact that its a "trivial" problem, but the solution is unnecessary, when my solution is much better,

- Klinoff Dev
